- name: changing /etc/profile file 
  block:
    - name:  ssh timeout 
      blockinfile: 
        path: /etc/profile  
        insertafter: EOF 
        backup: yes
        state: present
        block: |
         “#This is a test block added by Ansible……Arunima Das”
          export TMOUT=1800

    - name: setting umask 
      lineinfile:
        path: /etc/profile 
        regex: "^umask"
        line: "umask 0077"
        state: present
